services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: dbook-app
    volumes:
      - ./:/app
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d"
      DEBUG: "{DEBUG:-true}"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_NAME: "${DB_DATABASE:-dbook}"
      DB_USER: "${DB_USER:-dbook}"
      DB_PASS: "${DB_PASS:-DBookPassword#0}"
      SMTP_HOST: "${SMTP_HOST:-mailhog}"
      SMTP_PORT: "${SMTP_PORT:-1025}"
      JWT_SECRET: "{JWT_SECRET:-your-secret-key}"
    working_dir: /app
    depends_on:
      - mysql
      - mailhog

  web:
    image: nginx:latest
    container_name: dbook-web
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: dbook-db
    ports:
      - ${DB_LOCAL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-RootPassword#1}"
      MYSQL_DATABASE: "${DB_DATABASE:-dbook}"
      MYSQL_USER: "${DB_USER:-dbook}"
      MYSQL_PASSWORD: "${DB_PASS:-DBookPassword#0}"
    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: dbook-mail
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP server

volumes:
  mysql-data:
    driver: local
