services:
  app:
    image: acdiasjunior/dbook-app
    container_name: dbook-app
    volumes:
      - ./:/app
      - ./docker/php/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment: &app-environment-variables
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d"
      DEBUG: "{DEBUG:-true}"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_NAME: "${DB_DATABASE:-dbook}"
      DB_USER: "${DB_USER:-dbook}"
      DB_PASS: "${DB_PASS:-DBookPassword#0}"
      SMTP_HOST: "${SMTP_HOST:-mailhog}"
      SMTP_PORT: "${SMTP_PORT:-1025}"
      RABBITMQ_HOST: "${RABBITMQ_HOST:-rabbitmq}"
      RABBITMQ_PORT: "${RABBITMQ_PORT:-5672}"
      RABBITMQ_USER: "${RABBITMQ_USER:-guest}"
      RABBITMQ_PASS: "${RABBITMQ_PASS:-guest}"
      JWT_SECRET: "{JWT_SECRET:-your-secret-key}"
      TZ: "${TIMEZONE:-America/Chicago}"
    working_dir: /app
    entrypoint: ['bash', '/usr/local/bin/entrypoint.sh']
    depends_on:
      - mysql

  web:
    image: nginx:latest
    container_name: dbook-web
    ports:
      - "8080:80"
    environment:
      TZ: "${TIMEZONE:-America/Chicago}"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: dbook-db
    ports:
      - ${DB_LOCAL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-RootPassword#1}"
      MYSQL_DATABASE: "${DB_DATABASE:-dbook}"
      MYSQL_USER: "${DB_USER:-dbook}"
      MYSQL_PASSWORD: "${DB_PASS:-DBookPassword#0}"
      TZ: "${TIMEZONE:-America/Chicago}"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: dbook-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-guest}"
      TZ: "${TIMEZONE:-America/Chicago}"

  supervisor:
    image: acdiasjunior/dbook-worker
    container_name: dbook-worker
    volumes:
      - ./:/app
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
    environment: *app-environment-variables
    working_dir: /app
    depends_on:
      - rabbitmq

  mailhog:
    image: acdiasjunior/mailhog
    container_name: dbook-mail
    environment:
      TZ: "${TIMEZONE:-America/Chicago}"
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP server

volumes:
  mysql-data:
    driver: local
